global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend Spring Boot Actuator endpoint
  - job_name: 'itsm-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['itsm-backend:8080']
